#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
sudo apt-get y update
sudo apt-get -y install haproxy

# edit config file
haproxy_config=\
"
frontend myfrontend
        bind *:80
        mode http
        default_backend mybackend
backend mybackend
        balance roundrobin
        server web-01 3.86.13.247:80 check
        server web-02 35.174.208.1:80 check
"
sudo echo "$haproxy_config" | tee -a /etc/haproxy/haproxy.cfg

# enable it to start by inint

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
